/* data-receive-action */
const RECEIVE_ORGANISATION_DATA = 'RECEIVE_ORGANISATION_DATA';
const RECEIVE_ORGANISATION_LIST = 'RECEIVE_ORGANISATION_LIST';
const RECEIVE_CONTACT_DATA = 'RECEIVE_CONTACT_DATA';
const RECEIVE_CONTACT_LIST = 'RECEIVE_CONTACT_LIST';

/* data-request-actions */
const GET_ORGANISATION_LIST = 'GET_ORGANISATION_LIST';
const GET_CONTACT_LIST = 'GET_CONTACT_LIST';

/* ui-actions */
const DELETE_CONTACT = 'DELETE_CONTACT';
const DELETE_ORGANISATION = 'DELETE_ORGANISATION';
const DESELECT_CONTACT = 'DESELECT_CONTACT';
const DESELECT_ORGANISATION = 'DESELECT_ORGANISATION';
const HIDE_CONTACT_CREATOR = 'HIDE_CONTACT_CREATOR';
const HIDE_CONTACT_EDITOR = 'HIDE_CONTACT_EDITOR';
const HIDE_ORGANISATION_CREATOR = 'HIDE_ORGANISATION_CREATOR';
const HIDE_ORGANISATION_EDITOR = 'HIDE_ORGANISATION_EDITOR';
const SELECT_CONTACT = 'SELECT_CONTACT';
const SELECT_ORGANISATION = 'SELECT_ORGANISATION';
const SHOW_CONTACT_CREATOR = 'SHOW_CONTACT_CREATOR';
const SHOW_CONTACT_EDITOR = 'SHOW_CONTACT_EDITOR';
const SHOW_ORGANISATION_CREATOR = 'SHOW_ORGANISATION_CREATOR';
const SHOW_ORGANISATION_EDITOR = 'SHOW_ORGANISATION_EDITOR';

/* form-actions */
const CLEAR_CONTACT_FORM_DATA = 'CLEAR_CONTACT_FORM_DATA';
const CLEAR_ORGANISATION_FORM_DATA = 'CLEAR_ORGANISATION_FORM_DATA';
const SET_CONTACT_FORM_FORENAME = 'SET_CONTACT_FORM_FORENAME';
const SET_CONTACT_FORM_SURNAME = 'SET_CONTACT_FORM_SURNAME';
const SET_CONTACT_FORM_ORGANISATION = 'SET_CONTACT_FORM_ORGANISATION';
const SET_CONTACT_FORM_TELEPHONE = 'SET_CONTACT_FORM_TELEPHONE';
const SET_CONTACT_FORM_EMAIL = 'SET_CONTACT_FORM_EMAIL';
const SET_DEFAULT_CONTACT_FORM_ORGANISATION = 'SET_DEFAULT_CONTACT_FORM_ORGANISATION';
const SET_ORGANISATION_FORM_NAME = 'SET_ORGANISATION_FORM_NAME';
const SET_ORGANISATION_FORM_TELEPHONE = 'SET_ORGANISATION_FORM_TELEPHONE';
const SET_ORGANISATION_FORM_EMAIL = 'SET_ORGANISATION_FORM_EMAIL';
const SUBMIT_CONTACT_EDIT = 'SUBMIT_CONTACT_EDIT';
const SUBMIT_CONTACT_FORM = 'SUBMIT_CONTACT_FORM';
const SUBMIT_ORGANISATION_EDIT = 'SUBMIT_CONTACT_EDIT';
const SUBMIT_ORGANISATION_FORM = 'SUBMIT_CONTACT_FORM';

export default {
  CLEAR_CONTACT_FORM_DATA,
  CLEAR_ORGANISATION_FORM_DATA,
  DELETE_CONTACT,
  DELETE_ORGANISATION,
  DESELECT_CONTACT,
  DESELECT_ORGANISATION,
  GET_ORGANISATION_LIST,
  GET_CONTACT_LIST,
  HIDE_CONTACT_CREATOR,
  HIDE_CONTACT_EDITOR,
  HIDE_ORGANISATION_CREATOR,
  HIDE_ORGANISATION_EDITOR,
  RECEIVE_ORGANISATION_DATA,
  RECEIVE_ORGANISATION_LIST,
  RECEIVE_CONTACT_DATA,
  RECEIVE_CONTACT_LIST,
  SELECT_CONTACT,
  SELECT_ORGANISATION,
  SET_CONTACT_FORM_FORENAME,
  SET_CONTACT_FORM_SURNAME,
  SET_CONTACT_FORM_ORGANISATION,
  SET_CONTACT_FORM_TELEPHONE,
  SET_CONTACT_FORM_EMAIL,
  SET_DEFAULT_CONTACT_FORM_ORGANISATION,
  SET_ORGANISATION_FORM_NAME,
  SET_ORGANISATION_FORM_TELEPHONE,
  SET_ORGANISATION_FORM_EMAIL,
  SHOW_CONTACT_CREATOR,
  SHOW_CONTACT_EDITOR,
  SHOW_ORGANISATION_CREATOR,
  SHOW_ORGANISATION_EDITOR,
  SUBMIT_CONTACT_EDIT,
  SUBMIT_CONTACT_FORM,
  SUBMIT_ORGANISATION_EDIT,
  SUBMIT_ORGANISATION_FORM,
};
