const DISPLAY_ORGANISATION = 'DISPLAY_ORGANISATION';
const DISPLAY_CONTACT = 'DISPLAY_CONTACT';
const DISPLAY_NONE = 'DISPLAY_NONE';

export default {
  DISPLAY_ORGANISATION,
  DISPLAY_CONTACT,
  DISPLAY_NONE,
};
